### ISSUE TITLE
Recaptcha automated testing

### ISSUE THREAD

**Issue by vdroznik** [genemu/GenemuFormBundle#215]
Is there a way to automate testing of form with recaptcha?
I tried to turn it off in config:

``` yaml
genemu_form:
    recaptcha:
        enabled: false
```

but this config assumes that recaptcha won't be used at all anywhere in the code.

I offer to introduce parameter, like:

``` yaml
genemu_form:
    recaptcha:
        test_mode: true
```

which will not render a captcha (or maybe render some placeholder) and validator will always return true.

I am ready to implement it, if the author is agree, and if there is no other way to test
