### ISSUE TITLE
Problem to connfigure uploadify.swf

### ISSUE THREAD

**Issue by klb-rodriguez** [genemu/GenemuFormBundle#291]
Hello, I'm triying to implement uploadify... but I have some erros when try to configure, the problem is the follow:

in my config yml paramters I write this:

``` YAML
genemu_form:
    file:
        swf:        '/bundles/minsalsim/js/uploadify/uploadify.swf'
        enabled:    true
        cancel_img: '/bundles/genemuform/images/cancel.png'
        folder:     '/uploads/documents/docAdquisicion'
```

with this configuration I get this error:

```
http://web.sim.localhost/bundles/minsalsim/js/uploadify/uploadify.swf?preventswfcaching=1376498615336 404 (Not Found) 
```

and the swf not work, but if I change the "/" for "\" in the swf parameter:

``` YAML
swf:        '\bundles\minsalsim\js\uploadify\uploadify.swf'
```

the swf work but I get this error:

```
GET http://web.sim.localhost/web/app_dev.php/admin/minsal/sim/inventariotecnico/ 404 (Not Found) 
```

I don't know why when I change the swf configuration it made a error in the routing url.

I'm using sonata admin bundle
these are my configurations:

routing.yml

``` YAML
genemu_upload:
    resource: "@GenemuFormBundle/Resources/config/routing/upload.xml"
```

Admin class:

``` PHP
protected function configureFormFields(FormMapper $formMapper) {

        $formMapper
           //...
            ->add('docAdquisicion', 'genemu_jqueryfile'))
        ;
    }
```

my layout

``` TWIG
<!--CSS-->
        <link rel="stylesheet" href="{{ asset('bundles/minsalsim/js/uploadify/uploadify.css') }}" type="text/css" media="all" />

        {% if form is defined %}
            {{ form_stylesheet(form) }}
        {% endif %}
        {% endblock %}

<!--JS-->
        <script src="{{ asset('bundles/minsalsim/js/uploadify/jquery.uploadify.min.js') }}" type="text/javascript"></script>

        {% if form is defined %}
            {{ form_javascript(form) }}
        {% endif %}
        {% endblock %}
```
