### ISSUE TITLE
Failed to load resource (swf)

### ISSUE THREAD

**Issue by DeluxZ** [genemu/GenemuFormBundle#85]
I'm trying to use you bundle in my project to upload an image to the server.

``` yml
# config.yml
genemu_form:
    file:
        enabled:  true
        uploader: /static/uploadify/uploadify.swf
```

``` yml
# routing.yml
genemu_upload:
    resource: "@GenemuFormBundle/Controller/UploadController.php"
    type:     annotation
```

``` php
// FormType.php
public function buildForm(FormBuilder $builder, array $options)
{
    $builder->add('image', 'genemu_jqueryfile');
}
```

``` twig
{# in my form file #}
<link rel="stylesheet" type="text/css" href="{{ asset('/static/uploadify/uploadify.css') }}" />
{{ form_stylesheet(form) }}

<script src="{{ asset('/static/uploadify/jquery.uploadify.js') }}" type="text/javascript"></script>
{{ form_javascript(form) }}
```

When I load the page it shows the SELECT FILES button, but the SWF isn't loaded. When I check my developer console I see the following error:

Failed to load resource: the server responded with a status of 500 (Internal Server Error). The resource is the uploadify.swf, but it's trying to load it from app_dev.php/route/uploadify.swf instead of app_dev.php/static/uploadify/uploadify.swf
