### ISSUE TITLE
Getting uploadify.swf in wrong path

### ISSUE THREAD

**Issue by soullivaneuh** [genemu/GenemuFormBundle#95]
I put uploadify.swf into web/swf/

In my config file, I put :

``` yaml
genemu_form:
  image: ~
  file:
    uploader: /swf/uploadify.swf
```

I added 'genemu_jqueryimage' in my form model and include all stylesheets ans javascript, when I try to load profile_edit page, I have the uploadify image input, but I can do nothing and I have this error into the console :

```
GET http://localsf2.dowith.fr/app_dev.php/profile/uploadify.swf?preventswfcaching=1338216405943 404 (Not Found)
```

So, the browser did'nt try to get uploadify.swl in /web/swf...

I did something wrong ?

Thanks for help.
